t1 = System.currentTimeMillis()
imp = IJ.getImage()
imps = ChannelSplitter.split(imp)
ch1A = imps[0].getProcessor().convertToFloat().getPixels()
ch2A = imps[1].getProcessor().convertToFloat().getPixels()
t2 = System.currentTimeMillis()
min1 = min(ch1A)
max1 = max(ch1A)
min2 = min(ch2A)
max2 = max(ch2A)
plot = Plot("Colocalization", "Lysozome", "Microtubule")
plot.setLimits(min1, max1*1.1, min2, max2*1.1) 
plot.addPoints(ch1A, ch2A, Plot.DOT)
plot.show()
IJ.log("Processing Time "+ str(t2-t1)+" [msec]")
